# region imports
from AlgorithmImports import *
# endregion
"""
Constants used throughout the QuantConnect options trading strategy.
This file centralizes all static values to make the code more maintainable.
"""

# === SCHEDULING CONSTANTS ===
DEFAULT_SCHEDULE_TIME_HOUR = 11
DEFAULT_SCHEDULE_TIME_MINUTE = 0
DEFAULT_SCHEDULE_REFERENCE = "SPY"

# === OPTION FILTER CONSTANTS ===
DEFAULT_DAYS_TO_EXPIRATION_MIN = 14
DEFAULT_DAYS_TO_EXPIRATION_MAX = 45
DEFAULT_STRIKES_BELOW = -2
DEFAULT_STRIKES_ABOVE = 1

# === POSITION SIZING CONSTANTS ===
DEFAULT_TARGET_DELTA_MIN = 0.25
DEFAULT_TARGET_DELTA_MAX = 0.75
DEFAULT_MAX_POSITION_SIZE = 0.20
DEFAULT_OPTION_FREQUENCY = "monthly"
DEFAULT_STOCK_WEIGHT = 0.25

# === PORTFOLIO CONSTANTS ===
DEFAULT_MAX_STOCKS = 5
DEFAULT_MAX_PORTFOLIO_RISK = 0.02
DEFAULT_MAX_DRAWDOWN = 0.15
DEFAULT_CORRELATION_THRESHOLD = 0.7

# === DATA HISTORY CONSTANTS ===
MAX_PRICE_HISTORY_LENGTH = 100
MAX_PNL_HISTORY_LENGTH = 100
DEFAULT_MAX_PNL_HISTORY_LENGTH = 100
CORRELATION_LOOKBACK_DAYS = 60

# === MARKET ANALYSIS CONSTANTS ===
VOLATILITY_LOW_THRESHOLD = 0.2
VOLATILITY_HIGH_THRESHOLD = 0.4
MARKET_SCORE_BULLISH_LOW_VOL = 5
MARKET_SCORE_BULLISH_NORMAL_VOL = 3
MARKET_SCORE_BEARISH_HIGH_VOL = -5
VOLATILITY_SCORE_LOW = 3
VOLATILITY_SCORE_HIGH = -3

# === RISK MANAGEMENT CONSTANTS ===
DEFAULT_WIN_RATE_THRESHOLD = 0.6
DEFAULT_VOLATILITY_FACTOR_THRESHOLD = 0.3
DEFAULT_MAX_CONSECUTIVE_LOSSES = 3
DEFAULT_VOLATILITY_LOOKBACK = 20
DEFAULT_VOLATILITY_THRESHOLD = 0.4

# === TRADING CONSTANTS ===
OPTION_CONTRACT_MULTIPLIER = 100
DEFAULT_ORDER_TICKET_TIMEOUT = 30

# === LOGGING CONSTANTS ===
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"

# === CONFIGURATION CONSTANTS ===
DEFAULT_TOTAL_CASH = 100000

# === PERFORMANCE METRICS CONSTANTS ===
SHARPE_RATIO_MIN_PERIODS = 2
PROFIT_FACTOR_MIN_TRADES = 1

# === FILE PATHS ===
CONFIG_DIR = "config/"
BACKUP_DIR = "backup/"
STORAGE_DIR = "storage/"
TESTS_DIR = "tests/"

# === ERROR MESSAGES ===
ERROR_NO_STOCKS_AVAILABLE = "No stocks available for scheduling"
ERROR_CONFIG_LOAD_FAILED = "Failed to load configuration"
ERROR_POSITION_ENTRY_FAILED = "Failed to enter position"
ERROR_POSITION_EXIT_FAILED = "Failed to exit position"
ERROR_DATA_UPDATE_FAILED = "Failed to update data"

# === SUCCESS MESSAGES ===
SUCCESS_STRATEGY_INITIALIZED = "Strategy initialized successfully"
SUCCESS_POSITION_ENTERED = "Position entered successfully"
SUCCESS_POSITION_CLOSED = "Position closed successfully"
SUCCESS_DATA_UPDATED = "Data updated successfully"

